name: "SDKMAN! Release Action"
author: "hamzaremmal"
description: "Release your sdk to SDKMAN! using GitHub Actions"
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  consumer-key:
    description: "SDKMAN! consumer key"
    required: true
  consumer-token:
    description: "SDKMAN! consumer token"
    required: true
  candidate:
    description: "Candidate name"
    required: true
  version:
    description: "Version to release"
    required: true
  url:
    description: "Download URL"
    required: true
  platform:
    description: "Platform identifier"
    required: false
    default: "UNIVERSAL"
  checksum-md5:
    description: "MD5 checksum"
    required: false
  checksum-sha-1:
    description: "SHA-1 checksum"
    required: false
  checksum-sha-224:
    description: "SHA-224 checksum"
    required: false
  checksum-sha-256:
    description: "SHA-256 checksum"
    required: false
  checksum-sha-384:
    description: "SHA-384 checksum"
    required: false
  checksum-sha-512:
    description: "SHA-512 checksum"
    required: false
  backend:
    description: "Backend URL"
    required: false
    default: "https://vendors.sdkman.io"

## TODO: ADD THE OUTPUTS ?

runs:
  using: "node20"
  main: "dist/index.js"
